### ISSUE TITLE
Done button not working

### ISSUE THREAD

**Issue by An-png** [fonol/anki-search-inside-add-card#110]
It doesn't change the queue position of a note/PDF anymore. Only creating an extract does.

**Comment by An-png** [comment]
The Done button seems to work now. On top of this, the queue is very fast moving compared to before (or at least it seems this way).

What exactly did you change with the queue system in yesterday's update?

**Comment by fonol** [comment]
The calculation for items last seen >= 1 day ago stays the same, items you did today are ordered by their time last seen only and get rather small scores in the calculation. Not really that elegant, but it prevents a "lock" situation where all items have a small "last done" timestamp and so the same high priority items stick to the front of the queue.
This also means though that items done today are basically guaranteed to come up a second time on the same day only after all items with a "time since done last" >= 1 day have been done. Which you may find good or not. 
If you have a nice formula to calculate the positions of the items, based on the variables available, which are priority, last done timestamp, read pages when last done (not used atm), please suggest.

**Comment by An-png** [comment]
Thank you for the info :+1:
