### ISSUE TITLE
Search doesn't work.

### ISSUE THREAD

**Issue by dummifiedme** [fonol/anki-search-inside-add-card#132]
Not to complain but the search doesn't work!
I had created this card yesterday, I was making a card on the same topic and the searh never produced a result. No in the pdf not in the search outself with browser mode on. 

Then I searched for it in Browser, it indeed was there.

**Comment by fonol** [comment]
Hi, I would need some more information:
1. Does the add-on find no notes at all, or are only some notes not found?
2. If you can find the note in the Browser window, then you should at least be able to find it in the search bar, with "Mode: Browser", because that mode uses the exactly same search as the Browser window. Are you sure it didn't come up even if you type some exact same words from the note?
3. Did you have the deck selected (in the dropdown on the top) where the note is located in?
