### ISSUE TITLE
Error while updating

### ISSUE THREAD

**Issue by galantra** [fonol/anki-search-inside-add-card#134]
> Version 2.1.22 (0ecc189a)
> Python 3.8.0 Qt 5.14.1 PyQt 5.14.1

When I was updating add-ons today, the loading bar got stuck and an error message appeared, saying:

```
Unable to update or delete add-on. Please start Anki while holding down the shift key to temporarily disable add-ons, then try again.
Debug info: [WinError 124] None: 'C:\\Users\\user\ \PORTAB~1\\ANKIPO~1\\Anki2\\addons21\\178129~1'
```

I restarted Anki _without_ Shift held down and I got an error on startup:

```
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.
When loading 'Searching PDF Reading Note-Taking in Add Dialog':
Traceback (most recent call last):
File "aqt\addons.py", line 208, in loadAddons
File "C:
\Users\user\PortableApps\AnkiPortable\Anki2\addons21\1781298089\_init__.py",
line 4, in <module>
from . import src
File "C:
\Users\user\PortableApps\AnkiPortable\Anki2\addons21\1781298089\src\_init_.py", line 485, in <module>
init_addon()
File "C:
\Users\user\PortableApps\AnkiPortable\Anki2\addons21\1781298089\src\_init_.py", line 70, in init_addon
state.db_file_existed = create_db_file_if_not_existsO
File "C:
\Users\user\PortableApps\AnkiPortable\Anki2\addons21\1781298089\src\notes.py", line 76, in create_db_file_if_not_exists
conn = sqlite3.connect(file_path)
sqliteS.OperationalError: unable to open database file
```

**Comment by fonol** [comment]
Hi, that error has been coming up for quite some people recently. I suspect what happens is the following: 
1. Anki tries to update the add-on but the add-on's database file is used while doing that.
2. The database file is locked/corrupted/? in the process

I don't know exactly how to prevent that for future updates though. It might be enough to not store the `siac-notes.db` file in the addon's `user_files` folder so that it is not touched at all on updating.
If you re-install the add-on, it will work again. Of course if you have data (e.g. PDF reading progress) that you don't want to lose, you could try 
1. looking for processes that might hold the db file (or simply rebooting your machine to be sure)
2. copy the file, delete the original, try starting Anki with the copy

**Comment by fonol** [comment]
Should be fixed now with the newest update. (The error might still pop up one last time though after the update).
#137 #138

**Comment by galantra** [comment]
Thank you! I had to create a folder called "user_files". Now everything works again.
