### ISSUE TITLE
Simulating study sessions given notes and priority queue to see what configs are doing

### ISSUE THREAD

**Issue by elvis-sik** [fonol/anki-search-inside-add-card#219]
First of all, thank you for the addon. I decided to try it out this weekend and as a total noob would really benefit from a way to visualize what my configs will have me doing. That is, suppose I create several notes (add PDFs to the addon) and assign different priorities to them and don't touch the settings. Assuming I'll have one study session per day during the next 20 days, what will I be studying in those 20 sessions?

I read the func `_calc_score` and now I'm making these experiments manually to get these answers. I know the actual scheduling of notes is more complicated because the addon supports workflows more complex than simply assigning a priority and letting the queue take care of everything, but I think simulation would still be possible and useful.

**Comment by fonol** [comment]
Hi, 
the score the add-on just a really crude function which wasn't evaluated in any methodical way. I simply tested and when the results seemed reasonable enough, it was okay for me.  I remember it is just a linear function (input = time delta since last done) whose slope is determined by the priority you give.
I guess simulating to find a more elegant or better way of scoring would be nice, but at the moment, the thing works for me, so I wouldn't put it up really high on my list. But if you think you found a better way of scoring, I'd happily try it out and/or integrate it :).

> I know the actual scheduling of notes is more complicated because the addon supports workflows more complex than simply assigning a priority

There are only two other things that influence the order: There are these special schedules that you can give, these all just mean that at the day on which they are due, they are put on the beginning of the queue. Then there is the Postpone button which simply moves the item back some places after its score is calculated.

**Comment by elvis-sik** [comment]
I just wanted to share the idea so I'll close this at the moment. Again, thank you for your work.
