### ISSUE TITLE
Could not find 'Pages read' and 'Stats' in the UI

### ISSUE THREAD

**Issue by lb19940508** [fonol/anki-search-inside-add-card#227]
Thanks in advance, this add-on helps me a lot in implementing the incremental reading method. However I encountered some small confusions as followed.

**Problem description**
> Hi, it is in the sidebar that can be toggled by clicking on "NOTES", under "Read Stats".

I've read that 'Pages read' is in the **sidebar** in the add-on description page, however I couldn't find it, along with the 'Stats'. Neither in the initial interface when the add-on is first opened, nor in the reading mode when a PDF is opend

**Expected behavior**
- So, would you please specify where these info (both **'Pages read' and 'Stats'** ) could be found, or they are already outdated?
- BTW, would you please explain a little bit about the difference between **Read next** and 'Read[Rnd]', or give a documentation/link about those functions that users could refer to ?
<img width="348" alt="image" src="https://user-images.githubusercontent.com/34482511/109186956-6830e280-77cc-11eb-9f30-800ff55e07fd.png">

**Screenshots**
In the initial interface
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/34482511/109186617-125c3a80-77cc-11eb-9f0d-663dc7fc33e7.png">

In reading mode
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/34482511/109186239-aed20d00-77cb-11eb-9ea8-c353db9b3e63.png">

**Environment (please complete the following information):**
 - OS: [Mac OS]
 - Anki version (2.1.35)

Really appreciate your working on this add-on, looking forward for your reply.

Best Regards

**Comment by fonol** [comment]
Hi,
In general, some information on the add-on page might be outdated because I rather often changed parts of the UI.

> I've read that 'Pages read' is in the sidebar in the add-on description page, however I couldn't find it, along with the 'Stats'. 

What was meant with that was the `Read Stats` menu item in the sidebar. You already have identified the correct sidebar in your first screenshot,
you just have to switch to `Add-on Notes`.
![image](https://user-images.githubusercontent.com/22644769/109264187-dbeee180-7804-11eb-904e-73c2be3b8f20.png)

`Read Next` is the same as this button:
![image](https://user-images.githubusercontent.com/22644769/109264376-30925c80-7805-11eb-9fc2-94fe52845d99.png)
It just opens the first item in the queue. 

`Read [Rnd]` just opens a random item in the queue. This is kind of a legacy button from the very beginning which I don't use that often anymore, but I keep it in case someone finds it useful.

**Comment by lb19940508** [comment]
Thanks for the patient going though. 
The `Read Stats` is a really cool feature, and it's rather inspiring just like the `Review Heatmap` add-on.
Thank you again for the development of this handy add-on.
Best Regards.
