### ISSUE TITLE
indexing on demand

### ISSUE THREAD

**Issue by omega3** [fonol/anki-search-inside-add-card#29]
Index is build every Anki start. Normally it takes for my deck about 1 minute, with FTS option true, about 15 seconds.

But I don't add cards every Anki session or even when I add or do some editing, not always it is very important. 
Although this add-on is wonderful and very useful, its usage doesn't justify being forced to wait a minute every time I want to do my Anki session or perhaps only add some cards when I read something on the Internet.  

Would it be possible to disable indexing at every start and add button, so that users can decide when it is convenient for them to rebuild index?

**Comment by fonol** [comment]
How fast does FTS build the index for you? In your screenshots I saw that your collection is like ~10k notes.
Mine is 13k, and the FTS index builds in 5-10s. 
I totally agree that 30+ seconds is not worth the waiting, thats why I set the default index used to SQLite FTS instead of Whoosh for all new users.

**Comment by fonol** [comment]
Possible with newest version, so I am gonna close this issue.
