### ISSUE TITLE
Can't resize text boxes horizontally

### ISSUE THREAD

**Issue by aidanbunachita** [fonol/anki-search-inside-add-card#297]
I'm in Windows 10 & the most recent version of Anki and whenever I add text boxes, I can only extend them downwards (they don't resize horizontally). I know this is (or at least used to be) a feature because I saw AnKing do it in his tutorial video explaining how to use this add-on.

Any potential fixes? This is true for all text boxes I create in all the PDF's I have.

**Comment by 51Collect** [comment]
I am also having the same issue on MacOS, Anki 2.1.49, on the latest version of the add-on.

**Comment by fonol** [comment]
Hi, 
thanks for the reports, the problem will be fixed with the next version. 
The next update on Ankiweb might still need to wait for some time, as I am still fixing breakages caused by the latest development version (2.1.50). I will wait until the next major update to Anki including the update to Qt 6 is published and the editor reaches a stable state. Please also note if you get the add-on from Github, that with the current development state, the add-on will lose backwards compatibility with Anki versions < 2.1.50 (as noted in the addon's startup screen, I will focus on supporting the latest Anki versions due to time constraints).

**Comment by OcileCollection** [comment]
@fonol would you recommend installing the Qt 6 version or update to the Qt 5 version?

"Please also note if you get the add-on from Github, that with the current development state, the add-on will lose backwards compatibility with Anki versions < 2.1.50" Does that mean there is a version that will not break with the update to 2.1.50?

I can't seem to launch the add-on with a fresh install of the Qt 5 version of Anki 2.1.50 now.

**Comment by OcileCollection** [comment]
Would it be possible to close this issue. It seems to be resolved with the latest updates.

**Comment by fonol** [comment]
Sure!
