### ISSUE TITLE
Exclude some field in the search

### ISSUE THREAD

**Issue by zombieagain** [fonol/anki-search-inside-add-card#32]
Hi, truly impressed by the addon. Can you add the possibility to exclude a field in the json file. I have a "Audio" filed with some crazy name from google translator and the search matches random letters in the audio file name. It would be nice if I could exclude the "Audio" field from the search. Thanks!

**Comment by fonol** [comment]
I agree that would be nice. I'll see if it is doable without increasing the index build time too much.

**Comment by fonol** [comment]
You can update your add-on and check if it works for you. I added some info on it on the add-on page.
It will still highlight text in excluded fields if it matches for now, so don't be confused, but it should work nevertheless.

**Comment by zombieagain** [comment]
Sorry for the late response, I was traveling without a laptop. I just tried this and it works great! Thank you for being so quick!

**Comment by Uitalo** [comment]
Is possible don't show excluded fields in preview?

**Comment by fonol** [comment]
> Is possible don't show excluded fields in preview?

Sorry, read that late, it is possible, I am unsure how much work it will be, if it's not that much, I will try to include it in the next bigger update.

**Comment by Uitalo** [comment]
Thank you.

**Comment by fonol** [comment]
It should work with the newest update.

**Comment by Uitalo** [comment]
Yes, it works very well, thanks.

**Comment by edoreld** [comment]
Hello,

I'm running the version from 26-10-19 and the option to ignore fields doesn't seem to be working.

OS: Mac Os X 

How to reproduce:
1. Install add-on with default settings
2. Restart Anki
3. Press the 'A' Key to add a new card. This opens the add-on's interface.
4. Go to "Settings & Info"
5. Go to "Settings"
6. Click on ["Set Fields"] button next to "Exclude note fields from search or display"
7. Deselected the field that I want to exclude
8. Click [Close] button. 
9. Click on "Settings & Info"
10. Rebuild Index
11. Search for a field under "Browser Search"

The field I just excluded is used for the browser search.

**Comment by fonol** [comment]
Hi, that is actually expected behaviour. As it is right now, the add-on has basically two ways to search:
The index that is built at startup, or the native search function of Anki. I have no control over Anki's search function, and don't want to patch anything in it. So the exclusion of fields is completely restricted to the addon's index. 
In short, these fields should be excluded when: 

- Search on typing is triggered
- Search on selection is triggered
- You click on the magnifying icon on a note

I admit it is kinda weird right now that the only way to trigger a search using the addon's index is to type text in the field or to select text, I think I am gonna include a way to toggle the search bar at the bottom between Anki's browser search and the addon's search.

**Comment by fonol** [comment]
I made the label above the input toggle between add-on search and browser search, so using add-on search, it should work as expected.

**Comment by edoreld** [comment]
I just tested and it works great, thanks for the quick fix!
