### ISSUE TITLE
Generating Text(not cloze) and change page number of an pdf fast

### ISSUE THREAD

**Issue by glitchlover** [fonol/anki-search-inside-add-card#49]
I love your add-on. It will be great if you add the following feature: 

- I like to jump to the page as I wish. e.g: I am in page 1 and now I want to go to page 100 
- A button for "Generating Text" by the side of "Generating Cloze" 

I hope what I am requesting is not impossible for you.
I must say you have done a great job.

anyways
thanks a lot,
Sami

**Comment by fonol** [comment]
Hi, the first is already possible: On the bottom right you can see an input, where you can write your page number and hit enter.

What should "Generate Text" do?

**Comment by glitchlover** [comment]
first of all i have tried to input page number but failed :(
here is what your addon looks like in my desk-
![image](https://user-images.githubusercontent.com/59877631/72448435-38e62e80-37e1-11ea-9acb-759c243c6d86.png)
![image](https://user-images.githubusercontent.com/59877631/72448600-7ba80680-37e1-11ea-9b8e-59c80d374028.png)
did any button went underneath other buttons?
Never thought it would be an issue
 
and about generate text-
I want generate plane text from exactly what i select from the pdf and send it to my fields  
actually generate cloze messes with my workflow 
so if you add this i can study quickly

thanks for the attention

**Comment by fonol** [comment]
The whole interface looks messed up. Just look at the screenshots on the add-on's description page, and then look at yours. There are several buttons missing (page back/forward, page input), some buttons are partially cut off, and there is a whole part of the bottom of the dialog missing (after "Read Next")... I can only guess what the issue is, but from looking at your sceenshots, I see that you use quite some add-ons that modify the editor, have you tried disabling these? Does it make a difference?
What is your screen size? The whole dialog seems a bit "cramped" in your screenshots.
Also, what is your Windows text scaling set to?

**Comment by glitchlover** [comment]
font set to 20px

**Comment by glitchlover** [comment]
ok i found the culprit now i can see other buttons
thanks!

**Comment by fonol** [comment]
There is a new update available, which includes a _Zoom_ option in the settings. You could try to set it to a smaller value (e.g. 0.9 or 0.8) to have a little bit more space on the screen in general.
