### ISSUE TITLE
Percentages not displaying properly

### ISSUE THREAD

**Issue by silentcicada1** [fonol/anki-search-inside-add-card#60]
When I enter the page that has the pdf's listed some of them are not displaying appropriately.

https://drive.google.com/open?id=1UYZEf28V1oeLlELEBli0_59GT1FcWw4V

Some display the pages read out of the total and others display pages read over a random number.

**Comment by fonol** [comment]
I also noticed that behaviour some time ago, but could not pin the error down exactly. If you open the pdf with the wrong counts, and Mark all Unread -> Mark all Read, the counts should be correct and stay that way. I reckon the error had something to do with the way pages read were stored in older versions. For me, it hasn't occurred in like two months, so I suspected it had been fixed. 
Some questions if you don't mind:
1. How long has it been since you read these pdfs? Does the error only occur on older ones?
2. Did you change the source field of some of them?
3. If you can remember, what buttons did you mainly use to mark as read / are there buttons you certainly did not use (that would help too)?

Anyway, I uploaded a new version with some small fixes related to that problem which you can try out.

**Comment by fonol** [comment]
On a sidenote, any reason you use night mode but not the night mode styling of the add-on?

**Comment by silentcicada1** [comment]
They are all loading properly now! Thank you for fixing that issue so quickly.
I am using 2.1.20 on Mac with the built in night mode and I haven't been able to figure out how to style it in night mode. Any suggestions?

**Comment by fonol** [comment]
There is a section in the "settings" dialog for night mode :)
